app:
  gitlab:
    url:
    token:
    pr:
      skippPrDaysPassCount: 60d
      regularMessagesTtl: 1d
  telegram:
    token:
    botName:
    proxyHost:
    proxyPort:
    proxyUser:
    proxyPassword:
  job:
    notifyAboutMergedPr: 0 * 7-19 * * MON-FRI
    notifyAboutOpenedPr: '0 */2 7-19 * * MON-FRI'
    deleteMessages: 0 59 23 * * *


spring:
  datasource:
    url: jdbc:h2:file:./db/pr_message;AUTO_SERVER=TRUE
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  logging.file: /logs/pr-bot.log

